export default function TermsPage() {
  return (
    <div style={wrap}>
      <h1 style={h1}>Terms of Service</h1>
      <p style={p}>
        By accessing or using AdPulse AI, you agree to these Terms of Service.
      </p>

      <h2 style={h2}>Service Description</h2>
      <p style={p}>
        AdPulse AI provides Google Ads-focused analysis, reporting, and
        optimization recommendations for advertisers, brands, and agencies.
      </p>

      <h2 style={h2}>User Responsibility</h2>
      <p style={p}>
        You are responsible for the information you provide, the accounts you
        connect, and the actions you take based on recommendations generated by
        the platform.
      </p>

      <h2 style={h2}>No Guarantee of Results</h2>
      <p style={p}>
        While we aim to provide useful recommendations, we do not guarantee
        specific advertising results, revenue, ROAS, or business outcomes.
      </p>

      <h2 style={h2}>Acceptable Use</h2>
      <p style={p}>
        You agree not to misuse the platform, attempt unauthorized access, or use
        the service for unlawful purposes.
      </p>

      <h2 style={h2}>Payments and Plans</h2>
      <p style={p}>
        Paid plans, managed services, and subscriptions may be offered from time
        to time. Pricing, billing terms, and features may change with notice.
      </p>

      <h2 style={h2}>Limitation of Liability</h2>
      <p style={p}>
        AdPulse AI is not liable for direct or indirect losses arising from use of
        the platform, service interruptions, or decisions made based on platform
        insights.
      </p>

      <h2 style={h2}>Changes to Terms</h2>
      <p style={p}>
        We may update these terms at any time. Continued use of the platform means
        you accept the updated terms.
      </p>

      <h2 style={h2}>Contact</h2>
      <p style={p}>
        For questions about these terms, contact: <strong>support@yourdomain.com</strong>
      </p>
    </div>
  );
}

const wrap = {
  maxWidth: "900px",
  margin: "0 auto",
  padding: "48px 20px",
  lineHeight: 1.8,
  color: "#0f172a"
};

const h1 = {
  fontSize: "40px",
  marginBottom: "20px"
};

const h2 = {
  fontSize: "24px",
  marginTop: "28px",
  marginBottom: "10px"
};

const p = {
  color: "#475569",
  margin: 0
};
